### ISSUE TITLE
Check that {Datetime, DateTimeOffset and TimeSpan}.ToString(string format) uses InvariantCulture

### ISSUE THREAD

**Issue by jnyrup** [KThaulow/CodeAnalyzer#16]
Instead of e.g. 

```C#
DateTime.UtcNow.ToString("yyyy/MM/dd");
```
On my machine gives `"2018-08-14"`

use 
```C#
DateTime.UtcNow.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture);
```
On my machine gives `"2018/08/14"`

Reason:
When not using `InvariantCuture` the char `/` is interpreted as the [`DateSeparator`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.dateseparator?view=netframework-4.7.1#remarks) and is replaced with the the date separator of the current culture.

**Comment by KThaulow** [comment]
Check DateTimeOffset and TimeSpan as well

**Comment by KThaulow** [comment]
Analyzer for DateTimeOffset and TimeSpan added in commit 3b33de3d801bc566cc1960e2e836fa8d6f28c2e5
