### ISSUE TITLE
DateTime format checks

### ISSUE THREAD

**Issue by jnyrup** [KThaulow/CodeAnalyzer#21]
The following patterns (with any separator) should probably have `MM` (month) instead of `m` (minutes)
when formatting a `DateTime` or `DateTimeOffset`.

* `yyyy/mm/dd`
* `mm/dd/yyyy`
* `dd/mm/yyyy`
* `yy/mm/dd`
* `mm/dd/yy`
* `dd/mm/yy`

**Comment by KThaulow** [comment]
Added in commit ab3e16f09191dd6d4e004b293e6de33e495df13a
