### ISSUE TITLE
TimeSpan format checks

### ISSUE THREAD

**Issue by jnyrup** [KThaulow/CodeAnalyzer#22]
When formatting a `TimeSpan` using one the following is always invalid:

Year and month does not apply `TimeSpan`
* `y`
* `Y`
* `yy`
* `yyy`
* `yyyy`
* `M` "Did you mean `mm` (minutes)"
* `MM` "Did you mean `mm` (minutes)"
* `MMM`
* `MMMM`

`TimeSpan` doesn't operator with 12 vs 24h clock, so this is invalid:
* `HH` "Did you mean `hh` (hours)"

* `D` "Did you mean `dd` (days)"
* `DD` "Did you mean `dd` (days)"

Special cases:
* `d` alone doesn't work, use `%d` or in a pattern `@"d\:h"`
* `h` alone doesn't work, use `%h` or in a pattern `@"h\:m"`
* `m` alone doesn't work, use `%d` or in a pattern `@"m\:s"`
* `s` alone doesn't work, use `%s` or in a pattern `@"s\:f"`
* `f` alone doesn't work, use `%f` or in a pattern `@"f\:ff"`
* `F` alone doesn't work, use `%F` or in a pattern `@"F\:ff"`

**Comment by KThaulow** [comment]
Added in 11da1941b733cf6b3a5423ce0268175c61af05bf
